### ISSUE TITLE
[2pt] - Reserve form page

### ISSUE THREAD

**Issue by Wineshuga** [tan12082001/Vehicle-Booking-App-Backend#9]
The following should be implemented: 

* To reserve an appointment, the user has to select a date and city (username and selected item are auto-filled).

* Use the design based on the ["Book a vespa test-ride"](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005583) and add all necessary inputs.

* The user can also access the "Reserve" page from the navigation panel. In that case, only the username is auto-filled.
* 

![Image](https://github.com/tan12082001/Vehical-Appointment-App-Backend/assets/81354942/3ff33616-b18b-42a5-b2b7-d7239ee0cb34)

**Comment by tan12082001** [comment]
# Pull request: https://github.com/tan12082001/Vehicle-Booking-App-Frontend/pull/4
